Repository JuliaTesting/Aqua.jl, pull requests merged in 2024-10, with the labels that each got.

#299 Add dependabot for github-actions
  .github/dependabot.yml
Labels: no changelog, ci

#304 Update dependabot.yml
  .github/dependabot.yml
Labels: no changelog, ci

#298 Update CI for julia 1.11 release
  .github/workflows/test.yml
Labels: no changelog, ci

#297 Expand and clarify docs on persistent tasks
  CHANGELOG.md
  Project.toml
  docs/src/persistent_tasks.md
Labels: docs, test: persistent tasks

#309 remove Base and Core from ambiguities test
  CHANGELOG.md
  Project.toml
  src/Aqua.jl
Labels: test: ambiguities
