Repository JuliaTesting/Aqua.jl, pull requests merged in 2025-05, with the labels that each got.

#313 feat: add test to detect public names without a docstring
  CHANGELOG.md
  docs/make.jl
  docs/src/undocumented_names.md
  src/Aqua.jl
  src/undocumented_names.jl
  test/pkgs/PkgWithUndocumentedNames.jl
  test/pkgs/PkgWithUndocumentedNamesInSubmodule.jl
  test/pkgs/PkgWithoutUndocumentedNames.jl
  test/test_undocumented_names.jl
Labels: enhancement, new test, changelog: added

#330 Bump version to 0.8.12
  CHANGELOG.md
  Project.toml
Labels: release

#328 Prepare master to 1.0; update minimum julia version to 1.6
  .github/workflows/test.yml
  CHANGELOG.md
  Project.toml
  src/Aqua.jl
  src/piracies.jl
  src/pkg/LICENSE.md
  src/pkg/Versions.jl
  src/unbound_args.jl
  test/pkgs/PkgWithAmbiguities.jl
  test/test_ambiguities.jl
Labels: BREAKING, changelog: added

#332 Don't create testset if no test to run
  src/Aqua.jl
Labels: changelog: not needed

#335 Run CI on `release-*` branches
  .github/workflows/docs.yml
  .github/workflows/test.yml
Labels: changelog: not needed, ci, backport-0.8

#334 update piracies code to support v1.12 changes
  CHANGELOG.md
  src/piracies.jl
Labels: test: piracy, changelog: added, backport-0.8

#337 [release-0.8] Set version to 0.8.13
  CHANGELOG.md
  Project.toml
Labels: release
